[
    {"level": 1, "command": "/a", "description": "чат администрации"},
    {"level": 1, "command": "/ac", "description": "вызвать администратор"},
    {"level": 1, "command": "/admins", "description": "список админов"},
    {"level": 1, "command": "/ahelp", "description": "список команд"},
    {"level": 1, "command": "/pm", "description": "ответить на репорт"},
    {"level": 1, "command": "/slap", "description": "подбросить игрока"},
    {"level": 1, "command": "/sp", "description": "следить за игроком"},
    {"level": 1, "command": "/tdo_delete", "description": "удалить инфо"},
    {"level": 1, "command": "/z", "description": "ответить на запрос"},

    {"level": 2, "command": "/ac", "description": "чат саппортов"},
    {"level": 2, "command": "/back", "description": "вернуться"},
    {"level": 2, "command": "/fixcar", "description": "починить авто"},
    {"level": 2, "command": "/flip", "description": "восстановить ТС"},
    {"level": 2, "command": "/fly", "description": "режим полета"},
    {"level": 2, "command": "/getcar", "description": "телепорт авто"},
    {"level": 2, "command": "/gh", "description": "подменить ник"},
    {"level": 2, "command": "/goto", "description": "телепорт к игроку"},
    {"level": 2, "command": "/hp", "description": "установить ХП"},
    {"level": 2, "command": "/jail", "description": "деморган"},
    {"level": 2, "command": "/kick", "description": "кикнуть"},
    {"level": 2, "command": "/kjail", "description": "КПЗ"},
    {"level": 2, "command": "/mute", "description": "затычка"},
    {"level": 2, "command": "/online", "description": "онлайн фракций"},
    {"level": 2, "command": "/reset_table", "description": "сброс столов"},
    {"level": 2, "command": "/rmute", "description": "затычка репорта"},
    {"level": 2, "command": "/spawn", "description": "заспавнить"},
    {"level": 2, "command": "/spcar", "description": "заспавнить авто"},
    {"level": 2, "command": "/stats", "description": "статистика"},
    {"level": 2, "command": "/tplist", "description": "точки телепорта"},
    {"level": 2, "command": "/tplist_add", "description": "добавить ТП"},
    {"level": 2, "command": "/tplist_del", "description": "удалить ТП"},
    {"level": 2, "command": "/truckers_radio", "description": "рация"},
    {"level": 2, "command": "/unjail", "description": "выпустить"},
    {"level": 2, "command": "/unmute", "description": "снять затычку"},
    {"level": 2, "command": "/unrmute", "description": "снять затычку"},
    {"level": 2, "command": "/v_mute", "description": "мут войса"},
    {"level": 2, "command": "/v_unmute", "description": "снять мут"},
    {"level": 2, "command": "/unfmute", "description": "снять затычку"},
    {"level": 2, "command": "/set_vw", "description": "сменить VW"},

    {"level": 3, "command": "/a_boombox_delete", "description": ""},
    {"level": 3, "command": "/a_notify", "description": "уведомление"},
    {"level": 3, "command": "/aputveh", "description": "сесть за руль"},
    {"level": 3, "command": "/ban", "description": "забанить"},
    {"level": 3, "command": "/billboard_reset", "description": ""},
    {"level": 3, "command": "/biz", "description": "ТП к бизнесу"},
    {"level": 3, "command": "/delravito", "description": "удалить"},
    {"level": 3, "command": "/ears", "description": "прослушка СМС"},
    {"level": 3, "command": "/ent", "description": "ТП к подъезду"},
    {"level": 3, "command": "/evacuate_mhouse", "description": ""},
    {"level": 3, "command": "/fixcarall", "description": "починка"},
    {"level": 3, "command": "/gangs", "description": "список банд"},
    {"level": 3, "command": "/gar", "description": "ТП к гаражу"},
    {"level": 3, "command": "/gethere", "description": "телепорт"},
    {"level": 3, "command": "/gotocar", "description": "ТП к авто"},
    {"level": 3, "command": "/house", "description": "ТП к дому"},
    {"level": 3, "command": "/hp", "description": "установить ХП"},
    {"level": 3, "command": "/offban", "description": "бан офф"},
    {"level": 3, "command": "/offjail", "description": "джайл офф"},
    {"level": 3, "command": "/offwarn", "description": "варн офф"},
    {"level": 3, "command": "/nlist", "description": "смена ников"},
    {"level": 3, "command": "/respv", "description": "респавн авто"},
    {"level": 3, "command": "/spcars", "description": "заспавнить"},
    {"level": 3, "command": "/set_gps", "description": "маршрут"},
    {"level": 3, "command": "/time", "description": "время наказаний"},
    {"level": 3, "command": "/twarn", "description": "устный варн"},
    {"level": 3, "command": "/warn", "description": "варн"},

    {"level": 4, "command": "/acarpass", "description": "инфо авто"},
    {"level": 4, "command": "/alist", "description": "нарушения"},
    {"level": 4, "command": "/alock", "description": "открыть авто"},
    {"level": 4, "command": "/fban", "description": "блок IP"},
    {"level": 4, "command": "/fine_park", "description": "штраф"},
    {"level": 4, "command": "/hpall", "description": "выдать ХП"},
    {"level": 4, "command": "/mp_end", "description": "завершить МП"},
    {"level": 4, "command": "/mp_freeze", "description": "заморозка"},
    {"level": 4, "command": "/mp_get", "description": "телепорт"},
    {"level": 4, "command": "/mp_gun", "description": "выдать оружие"},
    {"level": 4, "command": "/mp_skin", "description": "скины"},
    {"level": 4, "command": "/mp_team", "description": "команды"},
    {"level": 4, "command": "/mp_tp", "description": "точка ТП"},
    {"level": 4, "command": "/msg (/o)", "description": "общий чат"},
    {"level": 4, "command": "/pos", "description": "ТП по коорд"},
    {"level": 4, "command": "/sban", "description": "тихий бан"},
    {"level": 4, "command": "/setfuel", "description": "заправить"},
    {"level": 4, "command": "/setpoint", "description": "точка ТП"},
    {"level": 4, "command": "/settime (/st)", "description": "время"},
    {"level": 4, "command": "/settp", "description": "открыть ТП"},
    {"level": 4, "command": "/setweather (/sw)", "description": ""},
    {"level": 4, "command": "/soffban", "description": "тихий бан"},
    {"level": 4, "command": "/templeader", "description": "лидер"},
    {"level": 4, "command": "/tpmark", "description": "ТП на точку"},
    {"level": 4, "command": "/unrban", "description": "разбан IP"},
    {"level": 4, "command": "/unwarn", "description": "снять варн"},
    {"level": 4, "command": "/veh", "description": "создать авто"},
    {"level": 4, "command": "/v", "description": "выдать авто"},
    {"level": 4, "command": "/vl_info", "description": "инфо ТС"}
]
